module.exports = {
  projects: [
    '<rootDir>/apps/review',
    '<rootDir>/apps/api',
    '<rootDir>/libs/api-interfaces',
    '<rootDir>/libs/review/ui-tile',
    '<rootDir>/libs/review/util-formatters',
    '<rootDir>/libs/review/data-access-games',
    '<rootDir>/libs/review/feature-lib',
    '<rootDir>/libs/review/feature-details',
    '<rootDir>/libs/review/feature-list',
    '<rootDir>/apps/store',
    '<rootDir>/libs/store/feature-list',
    '<rootDir>/libs/store/feature-details',
    '<rootDir>/libs/store/feature-cart',
    '<rootDir>/libs/store/ui-formatters',
    '<rootDir>/libs/store/data-access-games',
    '<rootDir>/libs/store/data-access-cart',
  ],
};
